### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by bkeyvani** [andrewschoen/django-cms-demo#7]
Hi. I was unable to complete the installation according to your instructions. I created the virtualenv just fine, activated the env, and proceeded to <pre>pip install -r requirements.txt</pre>

where I received the following error during installation.

<pre>clang -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -IlibImaging -I/Users/kbx4974e/Projects/DJANGO/django-cms/django-cms-demo/env/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _imaging.c -o build/temp.macosx-10.8-intel-2.7/_imaging.o

unable to execute clang: No such file or directory

error: command 'clang' failed with exit status 1</pre>

which happened right after <pre>copying PIL/XVThumbImagePlugin.py -> build/lib.macosx-10.8-intel-2.7/PIL

running build_ext

</pre>

I'm using OSX 10.8.4, python 2.7. I'd appreciate your input.

Thanks

**Comment by galeo** [comment]
It seems your system did't have the **clang** compiler installed,  try to install [Command Line Tools for Xcode](https://developer.apple.com/downloads) or [Xcode](http://itunes.apple.com/us/app/xcode/id497799835).

**Comment by bkeyvani** [comment]
Hey @galeo 
Probably a bit too late to thank you for your help and to mention that it resolved my question, and this issue can be closed. But a BIG THANK YOU very much for helping me back then when I knew nothing :blush:
